apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: object-detection-deployment
        image: object_detection_ahrar1
        imagePullPolicy: Never

        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5006


